httpClient:
    # The socket timeout value. If a read or write to the underlying
    # TCP/IP connection hasn't succeeded after this duration, a
    # timeout exception is thrown.
    timeout: 500ms

    # The connection timeout value. If a TCP/IP connection cannot be
    # established in this time, a timeout exception is thrown.
    connectionTimeout: 500ms

    # The time a TCP/IP connection to the server is allowed to
    # persist before being explicitly closed.
    timeToLive: 1 hour

    # If true, cookies will be persisted in memory for the duration
    # of the client's lifetime. If false, cookies will be ignored
    # entirely.
    cookiesEnabled: false

    # The maximum number of connections to be held in the client's
    # connection pool.
    maxConnections: 1024

    # The maximum number of connections per "route" to be held in
    # the client's connection pool. A route is essentially a
    # combination of hostname, port, configured proxies, etc.
    maxConnectionsPerRoute: 1024

    # The default value for a persistent connection's keep-alive.
    # A value of 0 will result in connections being immediately
    # closed after a response.
    keepAlive: 0s