---
- name: Install requirements
  yum: name={{ item }} state=present
  with_items:
      - gcc
      - make
      - openssl
      - openssl-devel
      - rpm-build
      - ruby
      - ruby-devel
      - rubygems

- name: Install gems
  gem: name={{ item }} state=latest
  with_items:
      - fpm
