Vagrant.require_version ">= 1.6.3"

Vagrant.configure(2) do |config|
  #
  # Global settings (overriden in VM config if needed)
  #
  config.vm.box = "chef/centos-6.6"
  # config.vm.box_url = ""
#  config.vbguest.auto_update = false

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.auto_detect = true
    config.cache.scope = :box
  end

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false

    vb.customize [ "modifyvm", :id,
      "--memory", "512"
    ]
  end


  config.vm.define "default", primary: true do |c|
    c.vm.hostname = "scb10x.dev"

    c.vm.network "private_network", ip: "192.168.0.100", netmask: "255.255.255.0"
#    c.vm.synced_folder ".", "/vagrant", disabled: true

    c.landrush.enabled = true
    c.landrush.upstream "8.8.8.8"
    c.landrush.upstream "127.0.1.1"

    c.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/playbook.yml"
      ansible.sudo = true
      ansible.verbose = "vv"
      ansible.groups = {
        "ci" => ["default"],
      }
    end
  end


  config.vm.define "ci", autostart: false do |c|
    c.vm.hostname = "scb10x-ci.dev"

    c.vm.network "private_network", ip: "192.168.0.10", netmask: "255.255.255.0"
    # c.vm.network "forwarded_port", guest: 80, host: 8080
    # c.vm.network "forwarded_port", guest: 8080, host: 8088

    c.landrush.enabled = true
    c.landrush.upstream "8.8.8.8"
    c.landrush.upstream "127.0.1.1"

    c.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/playbook.yml"
      ansible.sudo = true
      ansible.verbose = "vv"
      ansible.groups = {
        "ci" => ["default"],
      }
    end
  end


  config.vm.define "git", autostart: false do |c|
    c.vm.hostname = "scb10x-git.dev"

    c.vm.network "private_network", ip: "192.168.0.2", netmask: "255.255.255.0"

    c.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/playbook.yml"
      ansible.sudo = true
      ansible.verbose = "vv"
      ansible.groups = {
        "git" => ["default"],
      }
    end
  end


  config.vm.define "jira", autostart: false do |c|
    c.vm.hostname = "scb10x-jira.dev"

    c.vm.network "private_network", ip: "192.168.0.3", netmask: "255.255.255.0"

    c.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/playbook.yml"
      ansible.sudo = true
      ansible.verbose = "vv"
      ansible.groups = {
        "jira" => ["default"],
      }
    end
  end

end